apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-config-map
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx
      envFrom:
      - configMapRef:
          name: app-config