apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-secret-volume
spec:
  containers:
    - name: nginx
      image: nginx
  volumes:
    - name: app-secret-volume
      secret:
        secretName: api-secret