apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-single-env-from-secret
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: DB_Password
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: DB_Password
